<?php
 $emaillist = [
            array("email" => "imteyaz_bari@yahoo.com",
                "first_name" => "imteyaz_bari",
                "last_name" => "",
            ),
            array("email" => "myhongkongwork@yahoo.com",
                "first_name" => "myhongkongwork",
                "last_name" => "",
            ),
            array("email" => "workinmyhongkong@gmail.com",
                "first_name" => "workinmyhongkong",
                "last_name" => "",
            ),
            array("email" => "myjobinhongkong@gmail.com",
                "first_name" => "myjobinhongkong",
                "last_name" => "",
            ),
            array("email" => "bariimteyaz@gmail.com",
                "first_name" => "bariimteyaz",
                "last_name" => "",
            ),
            array("email" => "Hoor176@gmail.com",
                "first_name" => "Hoor176",
                "last_name" => "",
            ),
            array("email" => "Hoor176@yahoo.com",
                "first_name" => "Hoor176",
                "last_name" => "",
            ),
            array("email" => "octopuscartltd@gmail.com",
                "first_name" => "octopuscartltd",
                "last_name" => "",
            ),
            array("email" => "Tailor123hk@gmail.com",
                "first_name" => "Tailor123hk",
                "last_name" => "",
            ),
            array("email" => "costcointernationalltd@gmail.com",
                "first_name" => "costcointernationalltd",
                "last_name" => "",
            ),
            array("email" => "internationalcostco@gmail.com",
                "first_name" => "internationalcostco",
                "last_name" => "",
            ),
            array("email" => "softwaredeveloper.hk@gmail.com",
                "first_name" => "softwaredeveloper",
                "last_name" => "",
            ),
            array("email" => "tutor4allclasses@gmail.com",
                "first_name" => "tutor4allclasses",
                "last_name" => "",
            ),
            array("email" => "goodluckstar99@gmail.com",
                "first_name" => "goodluckstar99",
                "last_name" => "",
            ),
            array("email" => "bari.exporter@gmail.com",
                "first_name" => "bari",
                "last_name" => "",
            ),
            array("email" => "bariimteyazbari@gmail.com",
                "first_name" => "bariimteyazbari",
                "last_name" => "",
            ),
            array("email" => "sayedhk123@gmail.com",
                "first_name" => "sayedhk123",
                "last_name" => "",
            ),
            array("email" => "goodpetersam@yahoo.com",
                "first_name" => "goodpetersam",
                "last_name" => "",
            ),
            array("email" => "unitedtimepieceslimited@gmail.com",
                "first_name" => "unitedtimepieceslimited",
                "last_name" => "",
            ),
            array("email" => "kkpaul_p@yahoo.co.in",
                "first_name" => "kkpaul_p",
                "last_name" => "",
            ),
            array("email" => "sales@costcointernational.com",
                "first_name" => "sales",
                "last_name" => "",
            ),
            array("email" => "staras400@yahoo.co.in",
                "first_name" => "staras400",
                "last_name" => "",
            ),
            array("email" => "sales@octopuscart.com",
                "first_name" => "sales",
                "last_name" => "",
            ),
            array("email" => "lifeon366@gmail.com",
                "first_name" => "lifeon366",
                "last_name" => "",
            )
        ];
 
 $mailer_contacts = array(
                    "email"=>$emailaddr,
                    "first_name"=>$first_name,
                    "last_name"=>"",
                    "status"=>'1',
                    "mailer_list_id"=>10,
                    "datetime"=>""
                    );
                //$this->db->insert('mailer_contacts', $mailer_contacts);